project:
  type: website

website:
  title: "My Data Story Journey"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/neharika999
      - icon: linkedin
        href: https://www.linkedin.com/in/neharikashah2002/

format:
  html:
    theme: cerulean
    css: styles.css
    backgroundcolor: "#F5F5F5"



